// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Textplorer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidTextplorerPackageString = "e64854b0-7251-41a1-a31b-8ceb3afd5930";
        public static Guid guidTextplorerPackage = new Guid(guidTextplorerPackageString);

        public const string guidTextplorerPackageCmdSetString = "4d660e0f-2103-4882-af67-017cabd287b7";
        public static Guid guidTextplorerPackageCmdSet = new Guid(guidTextplorerPackageCmdSetString);

        public const string guidImagesString = "73afe43d-9f64-49bf-ba2d-1df053103e4e";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int searchCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}